# Generated by Django 5.0.6 on 2024-06-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolist_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='dateline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
